project:
  type: book
  output-dir: docs

book:
  title: "R Materials for Certificate Program"
  author: "Course Leadership Team"
  sidebar:
    style: docked
    pinned: true
    search: true
    collapse-level: 1
    logo: "images/UW-CHOICE LOGOS-01-White.png"
  chapters:
    - index.qmd
    - part: "Resources"
      chapters:
        - R_basics.qmd
        - run_locally.qmd
        - future_resources.qmd

format:
  html:
    page-layout: full
    theme: flatly
    css: uw-theme.css
    toc: true
    toc-depth: 3
